language: go

go:
- 1.16.x
- master

services:
  - postgresql

jobs:
  include:
    - stage: unit tests
      script: go test -v ./... -tags unit
    - stage: integration tests
      script: go test -v ./... -tags integration