language: go

go:
- 1.16.x
- master

services:
  - postgresql
  - docker

jobs:
  include:
    - stage: "Unit tests"
      name: unit tests
      script: go test -v ./... -tags unit
    
    - stage: "Integration tests"
      name: integration tests
      script: go test -v ./... -tags integration
    
    - stage: "Build docker container"
      name: "Build Dockerfile"
      script: docker build -t kwong21/graphql-go-cardkeeper .