language: go

go:
- 1.16.x
- master

services:
  - postgresql
  - docker

jobs:
  include:
    - stage: "Unit tests"
      name: unit tests
      script: go test -v ./... -tags unit
    
    - stage: "Integration tests"
      name: integration tests
      script: go test -v ./... -tags integration
    
    - stage: "Build docker container"
      name: "Build Dockerfile"
      script: docker build -t ${TRAVIS_REPO_SLUG} .

    - stage: "Push to ECR"
      if: tag IS present
      name: "Push to ECR if a tagged commit"
      script:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --region us-west-2 | docker login --username AWS --password-stdin 968977856753.dkr.ecr.us-west-2.amazonaws.com/deephalf_ecr)
        - docker build . --tag "${ECR_REPO}:latest" --tag "${ECR_REPO}:${TRAVIS_TAG}"
        - docker push "${ECR_REPO}:latest"
        - docker push "${ECR_REPO}:${TRAVIS_TAG}"
